export default [
  {  key: 'AF', flag: 'af', value: 'Afghanistan', text: 'Afghanistan', },
  {  key: 'AX', flag: 'ax', value: '\u00c5land Islands', text: '\u00c5land Islands', },
  {  key: 'AL', flag: 'al', value: 'Albania', text: 'Albania', },
  {  key: 'DZ', flag: 'dz', value: 'Algeria', text: 'Algeria', },
  {  key: 'AS', flag: 'as', value: 'American Samoa', text: 'American Samoa', },
  {  key: 'AD', flag: 'ad', value: 'Andorra', text: 'Andorra', },
  {  key: 'AO', flag: 'ao', value: 'Angola', text: 'Angola', },
  {  key: 'AI', flag: 'ai', value: 'Anguilla', text: 'Anguilla', },
  {  key: 'AG', flag: 'ag', value: 'Antigua & Barbuda', text: 'Antigua & Barbuda', },
  {  key: 'AR', flag: 'ar', value: 'Argentina', text: 'Argentina', },
  {  key: 'AM', flag: 'am', value: 'Armenia', text: 'Armenia', },
  {  key: 'AW', flag: 'aw', value: 'Aruba', text: 'Aruba', },
  {  key: 'AU', flag: 'au', value: 'Australia', text: 'Australia', },
  {  key: 'AT', flag: 'at', value: 'Austria', text: 'Austria', },
  {  key: 'AZ', flag: 'az', value: 'Azerbaijan', text: 'Azerbaijan', },
  {  key: 'BS', flag: 'bs', value: 'Bahamas', text: 'Bahamas', },
  {  key: 'BH', flag: 'bh', value: 'Bahrain', text: 'Bahrain', },
  {  key: 'BD', flag: 'bd', value: 'Bangladesh', text: 'Bangladesh', },
  {  key: 'BB', flag: 'bb', value: 'Barbados', text: 'Barbados', },
  {  key: 'BY', flag: 'by', value: 'Belarus', text: 'Belarus', },
  {  key: 'BE', flag: 'be', value: 'Belgium', text: 'Belgium', },
  {  key: 'BZ', flag: 'bz', value: 'Belize', text: 'Belize', },
  {  key: 'BJ', flag: 'bj', value: 'Benin', text: 'Benin', },
  {  key: 'BM', flag: 'bm', value: 'Bermuda', text: 'Bermuda', },
  {  key: 'BT', flag: 'bt', value: 'Bhutan', text: 'Bhutan', },
  {  key: 'BO', flag: 'bo', value: 'Bolivia', text: 'Bolivia', },
  {  key: 'BA', flag: 'ba', value: 'Bosnia & Herzegovina', text: 'Bosnia & Herzegovina', },
  {  key: 'BW', flag: 'bw', value: 'Botswana', text: 'Botswana', },
  {  key: 'BR', flag: 'br', value: 'Brazil', text: 'Brazil', },
  {  key: 'IO', flag: 'io', value: 'British Indian Ocean Territory', text: 'British Indian Ocean Territory', },
  {  key: 'VG', flag: 'vg', value: 'British Virgin Islands', text: 'British Virgin Islands', },
  {  key: 'BN', flag: 'bn', value: 'Brunei', text: 'Brunei', },
  {  key: 'BG', flag: 'bg', value: 'Bulgaria', text: 'Bulgaria', },
  {  key: 'BF', flag: 'bf', value: 'Burkina Faso', text: 'Burkina Faso', },
  {  key: 'BI', flag: 'bi', value: 'Burundi', text: 'Burundi', },
  {  key: 'KH', flag: 'kh', value: 'Cambodia', text: 'Cambodia', },
  {  key: 'CM', flag: 'cm', value: 'Cameroon', text: 'Cameroon', },
  {  key: 'CA', flag: 'ca', value: 'Canada', text: 'Canada', },
  {  key: 'CV', flag: 'cv', value: 'Cape Verde', text: 'Cape Verde', },
  {  key: 'KY', flag: 'ky', value: 'Cayman Islands', text: 'Cayman Islands', },
  {  key: 'CF', flag: 'cf', value: 'Central African Republic', text: 'Central African Republic', },
  {  key: 'TD', flag: 'td', value: 'Chad', text: 'Chad', },
  {  key: 'CL', flag: 'cl', value: 'Chile', text: 'Chile', },
  {  key: 'CN', flag: 'cn', value: 'China', text: 'China', },
  {  key: 'CX', flag: 'cx', value: 'Christmas Island', text: 'Christmas Island', },
  {  key: 'CC', flag: 'cc', value: 'Cocos (Keeling) Islands', text: 'Cocos (Keeling) Islands', },
  {  key: 'CO', flag: 'co', value: 'Colombia', text: 'Colombia', },
  {  key: 'KM', flag: 'km', value: 'Comoros', text: 'Comoros', },
  {  key: 'CG', flag: 'cg', value: 'Congo - Brazzaville', text: 'Congo - Brazzaville', },
  {  key: 'CD', flag: 'cd', value: 'Congo - Kinshasa', text: 'Congo - Kinshasa', },
  {  key: 'CK', flag: 'ck', value: 'Cook Islands', text: 'Cook Islands', },
  {  key: 'CR', flag: 'cr', value: 'Costa Rica', text: 'Costa Rica', },
  {  key: 'CI', flag: 'ci', value: 'C\u00f4te d\u2019Ivoire', text: 'C\u00f4te d\u2019Ivoire', },
  {  key: 'HR', flag: 'hr', value: 'Croatia', text: 'Croatia', },
  {  key: 'CU', flag: 'cu', value: 'Cuba', text: 'Cuba', },
  {  key: 'CY', flag: 'cy', value: 'Cyprus', text: 'Cyprus', },
  {  key: 'CZ', flag: 'cz', value: 'Czech Republic', text: 'Czech Republic', },
  {  key: 'DK', flag: 'dk', value: 'Denmark', text: 'Denmark', },
  {  key: 'DJ', flag: 'dj', value: 'Djibouti', text: 'Djibouti', },
  {  key: 'DM', flag: 'dm', value: 'Dominica', text: 'Dominica', },
  {  key: 'DO', flag: 'do', value: 'Dominican Republic', text: 'Dominican Republic', },
  {  key: 'EC', flag: 'ec', value: 'Ecuador', text: 'Ecuador', },
  {  key: 'EG', flag: 'eg', value: 'Egypt', text: 'Egypt', },
  {  key: 'SV', flag: 'sv', value: 'El Salvador', text: 'El Salvador', },
  {  key: 'GQ', flag: 'gq', value: 'Equatorial Guinea', text: 'Equatorial Guinea', },
  {  key: 'ER', flag: 'er', value: 'Eritrea', text: 'Eritrea', },
  {  key: 'EE', flag: 'ee', value: 'Estonia', text: 'Estonia', },
  {  key: 'ET', flag: 'et', value: 'Ethiopia', text: 'Ethiopia', },
  {  key: 'FK', flag: 'fk', value: 'Falkland Islands', text: 'Falkland Islands', },
  {  key: 'FO', flag: 'fo', value: 'Faroe Islands', text: 'Faroe Islands', },
  {  key: 'FJ', flag: 'fj', value: 'Fiji', text: 'Fiji', },
  {  key: 'FI', flag: 'fi', value: 'Finland', text: 'Finland', },
  {  key: 'FR', flag: 'fr', value: 'France', text: 'France', },
  {  key: 'GF', flag: 'gf', value: 'French Guiana', text: 'French Guiana', },
  {  key: 'PF', flag: 'pf', value: 'French Polynesia', text: 'French Polynesia', },
  {  key: 'TF', flag: 'tf', value: 'French Southern Territories', text: 'French Southern Territories', },
  {  key: 'GA', flag: 'ga', value: 'Gabon', text: 'Gabon', },
  {  key: 'GM', flag: 'gm', value: 'Gambia', text: 'Gambia', },
  {  key: 'GE', flag: 'ge', value: 'Georgia', text: 'Georgia', },
  {  key: 'DE', flag: 'de', value: 'Germany', text: 'Germany', },
  {  key: 'GH', flag: 'gh', value: 'Ghana', text: 'Ghana', },
  {  key: 'GI', flag: 'gi', value: 'Gibraltar', text: 'Gibraltar', },
  {  key: 'GR', flag: 'gr', value: 'Greece', text: 'Greece', },
  {  key: 'GL', flag: 'gl', value: 'Greenland', text: 'Greenland', },
  {  key: 'GD', flag: 'gd', value: 'Grenada', text: 'Grenada', },
  {  key: 'GP', flag: 'gp', value: 'Guadeloupe', text: 'Guadeloupe', },
  {  key: 'GU', flag: 'gu', value: 'Guam', text: 'Guam', },
  {  key: 'GT', flag: 'gt', value: 'Guatemala', text: 'Guatemala', },
  {  key: 'GN', flag: 'gn', value: 'Guinea', text: 'Guinea', },
  {  key: 'GW', flag: 'gw', value: 'Guinea-Bissau', text: 'Guinea-Bissau', },
  {  key: 'GY', flag: 'gy', value: 'Guyana', text: 'Guyana', },
  {  key: 'HT', flag: 'ht', value: 'Haiti', text: 'Haiti', },
  {  key: 'HN', flag: 'hn', value: 'Honduras', text: 'Honduras', },
  {  key: 'HK', flag: 'hk', value: 'Hong Kong SAR China', text: 'Hong Kong SAR China', },
  {  key: 'HU', flag: 'hu', value: 'Hungary', text: 'Hungary', },
  {  key: 'IS', flag: 'is', value: 'Iceland', text: 'Iceland', },
  {  key: 'IN', flag: 'in', value: 'India', text: 'India', },
  {  key: 'ID', flag: 'id', value: 'Indonesia', text: 'Indonesia', },
  {  key: 'IR', flag: 'ir', value: 'Iran', text: 'Iran', },
  {  key: 'IQ', flag: 'iq', value: 'Iraq', text: 'Iraq', },
  {  key: 'IE', flag: 'ie', value: 'Ireland', text: 'Ireland', },
  {  key: 'IL', flag: 'il', value: 'Israel', text: 'Israel', },
  {  key: 'IT', flag: 'it', value: 'Italy', text: 'Italy', },
  {  key: 'JM', flag: 'jm', value: 'Jamaica', text: 'Jamaica', },
  {  key: 'JP', flag: 'jp', value: 'Japan', text: 'Japan', },
  {  key: 'JO', flag: 'jo', value: 'Jordan', text: 'Jordan', },
  {  key: 'KZ', flag: 'kz', value: 'Kazakhstan', text: 'Kazakhstan', },
  {  key: 'KE', flag: 'ke', value: 'Kenya', text: 'Kenya', },
  {  key: 'KI', flag: 'ki', value: 'Kiribati', text: 'Kiribati', },
  {  key: 'KW', flag: 'kw', value: 'Kuwait', text: 'Kuwait', },
  {  key: 'KG', flag: 'kg', value: 'Kyrgyzstan', text: 'Kyrgyzstan', },
  {  key: 'LA', flag: 'la', value: 'Laos', text: 'Laos', },
  {  key: 'LV', flag: 'lv', value: 'Latvia', text: 'Latvia', },
  {  key: 'LB', flag: 'lb', value: 'Lebanon', text: 'Lebanon', },
  {  key: 'LS', flag: 'ls', value: 'Lesotho', text: 'Lesotho', },
  {  key: 'LR', flag: 'lr', value: 'Liberia', text: 'Liberia', },
  {  key: 'LY', flag: 'ly', value: 'Libya', text: 'Libya', },
  {  key: 'LI', flag: 'li', value: 'Liechtenstein', text: 'Liechtenstein', },
  {  key: 'LT', flag: 'lt', value: 'Lithuania', text: 'Lithuania', },
  {  key: 'LU', flag: 'lu', value: 'Luxembourg', text: 'Luxembourg', },
  {  key: 'MO', flag: 'mo', value: 'Macau SAR China', text: 'Macau SAR China', },
  {  key: 'MK', flag: 'mk', value: 'Macedonia', text: 'Macedonia', },
  {  key: 'MG', flag: 'mg', value: 'Madagascar', text: 'Madagascar', },
  {  key: 'MW', flag: 'mw', value: 'Malawi', text: 'Malawi', },
  {  key: 'MY', flag: 'my', value: 'Malaysia', text: 'Malaysia', },
  {  key: 'MV', flag: 'mv', value: 'Maldives', text: 'Maldives', },
  {  key: 'ML', flag: 'ml', value: 'Mali', text: 'Mali', },
  {  key: 'MT', flag: 'mt', value: 'Malta', text: 'Malta', },
  {  key: 'MH', flag: 'mh', value: 'Marshall Islands', text: 'Marshall Islands', },
  {  key: 'MQ', flag: 'mq', value: 'Martinique', text: 'Martinique', },
  {  key: 'MR', flag: 'mr', value: 'Mauritania', text: 'Mauritania', },
  {  key: 'MU', flag: 'mu', value: 'Mauritius', text: 'Mauritius', },
  {  key: 'YT', flag: 'yt', value: 'Mayotte', text: 'Mayotte', },
  {  key: 'MX', flag: 'mx', value: 'Mexico', text: 'Mexico', },
  {  key: 'FM', flag: 'fm', value: 'Micronesia', text: 'Micronesia', },
  {  key: 'MD', flag: 'md', value: 'Moldova', text: 'Moldova', },
  {  key: 'MC', flag: 'mc', value: 'Monaco', text: 'Monaco', },
  {  key: 'MN', flag: 'mn', value: 'Mongolia', text: 'Mongolia', },
  {  key: 'ME', flag: 'me', value: 'Montenegro', text: 'Montenegro', },
  {  key: 'MS', flag: 'ms', value: 'Montserrat', text: 'Montserrat', },
  {  key: 'MA', flag: 'ma', value: 'Morocco', text: 'Morocco', },
  {  key: 'MZ', flag: 'mz', value: 'Mozambique', text: 'Mozambique', },
  {  key: 'MM', flag: 'mm', value: 'Myanmar (Burma)', text: 'Myanmar (Burma)', },
  {  key: 'NA', flag: 'na', value: 'Namibia', text: 'Namibia', },
  {  key: 'NR', flag: 'nr', value: 'Nauru', text: 'Nauru', },
  {  key: 'NP', flag: 'np', value: 'Nepal', text: 'Nepal', },
  {  key: 'NL', flag: 'nl', value: 'Netherlands', text: 'Netherlands', },
  {  key: 'NC', flag: 'nc', value: 'New Caledonia', text: 'New Caledonia', },
  {  key: 'NZ', flag: 'nz', value: 'New Zealand', text: 'New Zealand', },
  {  key: 'NI', flag: 'ni', value: 'Nicaragua', text: 'Nicaragua', },
  {  key: 'NE', flag: 'ne', value: 'Niger', text: 'Niger', },
  {  key: 'NG', flag: 'ng', value: 'Nigeria', text: 'Nigeria', },
  {  key: 'NU', flag: 'nu', value: 'Niue', text: 'Niue', },
  {  key: 'NF', flag: 'nf', value: 'Norfolk Island', text: 'Norfolk Island', },
  {  key: 'KP', flag: 'kp', value: 'North Korea', text: 'North Korea', },
  {  key: 'MP', flag: 'mp', value: 'Northern Mariana Islands', text: 'Northern Mariana Islands', },
  {  key: 'NO', flag: 'no', value: 'Norway', text: 'Norway', },
  {  key: 'OM', flag: 'om', value: 'Oman', text: 'Oman', },
  {  key: 'PK', flag: 'pk', value: 'Pakistan', text: 'Pakistan', },
  {  key: 'PW', flag: 'pw', value: 'Palau', text: 'Palau', },
  {  key: 'PS', flag: 'ps', value: 'Palestinian Territories', text: 'Palestinian Territories', },
  {  key: 'PA', flag: 'pa', value: 'Panama', text: 'Panama', },
  {  key: 'PG', flag: 'pg', value: 'Papua New Guinea', text: 'Papua New Guinea', },
  {  key: 'PY', flag: 'py', value: 'Paraguay', text: 'Paraguay', },
  {  key: 'PE', flag: 'pe', value: 'Peru', text: 'Peru', },
  {  key: 'PH', flag: 'ph', value: 'Philippines', text: 'Philippines', },
  {  key: 'PN', flag: 'pn', value: 'Pitcairn Islands', text: 'Pitcairn Islands', },
  {  key: 'PL', flag: 'pl', value: 'Poland', text: 'Poland', },
  {  key: 'PT', flag: 'pt', value: 'Portugal', text: 'Portugal', },
  {  key: 'PR', flag: 'pr', value: 'Puerto Rico', text: 'Puerto Rico', },
  {  key: 'QA', flag: 'qa', value: 'Qatar', text: 'Qatar', },
  {  key: 'RE', flag: 're', value: 'R\u00e9union', text: 'R\u00e9union', },
  {  key: 'RO', flag: 'ro', value: 'Romania', text: 'Romania', },
  {  key: 'RU', flag: 'ru', value: 'Russia', text: 'Russia', },
  {  key: 'RW', flag: 'rw', value: 'Rwanda', text: 'Rwanda', },
  {  key: 'WS', flag: 'ws', value: 'Samoa', text: 'Samoa', },
  {  key: 'SM', flag: 'sm', value: 'San Marino', text: 'San Marino', },
  {  key: 'ST', flag: 'st', value: 'S\u00e3o Tom\u00e9 & Pr\u00edncipe', text: 'S\u00e3o Tom\u00e9 & Pr\u00edncipe', },
  {  key: 'SA', flag: 'sa', value: 'Saudi Arabia', text: 'Saudi Arabia', },
  {  key: 'SN', flag: 'sn', value: 'Senegal', text: 'Senegal', },
  {  key: 'RS', flag: 'rs', value: 'Serbia', text: 'Serbia', },
  {  key: 'SC', flag: 'sc', value: 'Seychelles', text: 'Seychelles', },
  {  key: 'SL', flag: 'sl', value: 'Sierra Leone', text: 'Sierra Leone', },
  {  key: 'SG', flag: 'sg', value: 'Singapore', text: 'Singapore', },
  {  key: 'SK', flag: 'sk', value: 'Slovakia', text: 'Slovakia', },
  {  key: 'SI', flag: 'si', value: 'Slovenia', text: 'Slovenia', },
  {  key: 'SB', flag: 'sb', value: 'Solomon Islands', text: 'Solomon Islands', },
  {  key: 'SO', flag: 'so', value: 'Somalia', text: 'Somalia', },
  {  key: 'ZA', flag: 'za', value: 'South Africa', text: 'South Africa', },
  {  key: 'GS', flag: 'gs', value: 'South Georgia & South Sandwich Islands', text: 'South Georgia & South Sandwich Islands', },
  {  key: 'KR', flag: 'kr', value: 'South Korea', text: 'South Korea', },
  {  key: 'ES', flag: 'es', value: 'Spain', text: 'Spain', },
  {  key: 'LK', flag: 'lk', value: 'Sri Lanka', text: 'Sri Lanka', },
  {  key: 'SH', flag: 'sh', value: 'St. Helena', text: 'St. Helena', },
  {  key: 'KN', flag: 'kn', value: 'St. Kitts & Nevis', text: 'St. Kitts & Nevis', },
  {  key: 'LC', flag: 'lc', value: 'St. Lucia', text: 'St. Lucia', },
  {  key: 'PM', flag: 'pm', value: 'St. Pierre & Miquelon', text: 'St. Pierre & Miquelon', },
  {  key: 'VC', flag: 'vc', value: 'St. Vincent & Grenadines', text: 'St. Vincent & Grenadines', },
  {  key: 'SD', flag: 'sd', value: 'Sudan', text: 'Sudan', },
  {  key: 'SR', flag: 'sr', value: 'Suriname', text: 'Suriname', },
  {  key: 'SJ', flag: 'sj', value: 'Svalbard & Jan Mayen', text: 'Svalbard & Jan Mayen', },
  {  key: 'SZ', flag: 'sz', value: 'Swaziland', text: 'Swaziland', },
  {  key: 'SE', flag: 'se', value: 'Sweden', text: 'Sweden', },
  {  key: 'CH', flag: 'ch', value: 'Switzerland', text: 'Switzerland', },
  {  key: 'SY', flag: 'sy', value: 'Syria', text: 'Syria', },
  {  key: 'TW', flag: 'tw', value: 'Taiwan', text: 'Taiwan', },
  {  key: 'TJ', flag: 'tj', value: 'Tajikistan', text: 'Tajikistan', },
  {  key: 'TZ', flag: 'tz', value: 'Tanzania', text: 'Tanzania', },
  {  key: 'TH', flag: 'th', value: 'Thailand', text: 'Thailand', },
  {  key: 'TL', flag: 'tl', value: 'Timor-Leste', text: 'Timor-Leste', },
  {  key: 'TG', flag: 'tg', value: 'Togo', text: 'Togo', },
  {  key: 'TK', flag: 'tk', value: 'Tokelau', text: 'Tokelau', },
  {  key: 'TO', flag: 'to', value: 'Tonga', text: 'Tonga', },
  {  key: 'TT', flag: 'tt', value: 'Trinidad & Tobago', text: 'Trinidad & Tobago', },
  {  key: 'TN', flag: 'tn', value: 'Tunisia', text: 'Tunisia', },
  {  key: 'TR', flag: 'tr', value: 'Turkey', text: 'Turkey', },
  {  key: 'TM', flag: 'tm', value: 'Turkmenistan', text: 'Turkmenistan', },
  {  key: 'TC', flag: 'tc', value: 'Turks & Caicos Islands', text: 'Turks & Caicos Islands', },
  {  key: 'TV', flag: 'tv', value: 'Tuvalu', text: 'Tuvalu', },
  {  key: 'UM', flag: 'um', value: 'U.S. Outlying Islands', text: 'U.S. Outlying Islands', },
  {  key: 'VI', flag: 'vi', value: 'U.S. Virgin Islands', text: 'U.S. Virgin Islands', },
  {  key: 'UG', flag: 'ug', value: 'Uganda', text: 'Uganda', },
  {  key: 'UA', flag: 'ua', value: 'Ukraine', text: 'Ukraine', },
  {  key: 'AE', flag: 'ae', value: 'United Arab Emirates', text: 'United Arab Emirates', },
  {  key: 'GB', flag: 'gb', value: 'United Kingdom', text: 'United Kingdom', },
  {  key: 'US', flag: 'us', value: 'United States', text: 'United States', },
  {  key: 'USM', flag: 'us', value: 'United States Minor Outlying Islands', text: 'United States Minor Outlying Islands', },
  {  key: 'UY', flag: 'uy', value: 'Uruguay', text: 'Uruguay', },
  {  key: 'UZ', flag: 'uz', value: 'Uzbekistan', text: 'Uzbekistan', },
  {  key: 'VU', flag: 'vu', value: 'Vanuatu', text: 'Vanuatu', },
  {  key: 'VA', flag: 'va', value: 'Vatican City', text: 'Vatican City', },
  {  key: 'VE', flag: 've', value: 'Venezuela', text: 'Venezuela', },
  {  key: 'VN', flag: 'vn', value: 'Vietnam', text: 'Vietnam', },
  {  key: 'WF', flag: 'wf', value: 'Wallis & Futuna', text: 'Wallis & Futuna', },
  {  key: 'EH', flag: 'eh', value: 'Western Sahara', text: 'Western Sahara', },
  {  key: 'YE', flag: 'ye', value: 'Yemen', text: 'Yemen', },
  {  key: 'ZM', flag: 'zm', value: 'Zambia', text: 'Zambia', },
  {  key: 'ZW', flag: 'zw', value: 'Zimbabw', text: 'Zimbabwe' },
]
